spring.application.name=oditji

server.port=8080
server.servlet.context-path=/oditji
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//8.230.20.118:1521/xe
spring.datasource.username=SYSTEM
spring.datasource.password=1234

mybatis.mapper-locations=classpath:/mybatis/mappers/**/*.xml
mybatis.type-aliases-package=com.project.oditji
mybatis.configuration.map-underscore-to-camel-case=true

# 파일 업로드 용량 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# PortOne V2 Credentials 공통
portone.store-id=store-090fa5e1-06cc-4925-b5a5-222ebf1649fc
portone.api-secret=bqInokEpdDwscLdShXOIeVt8w4EGxFNzXMRWXSsrZS3qRZuZjLdD5u4mPwa2vZp3cPbfLfCDs9YjLVQ3

# 본인간편인증 채널
portone.identity1.channel-key=channel-key-96e977d5-51b5-48ab-8609-a6f2d0850851

# 결제 채널
portone.payment.channel-key=channel-key-2131d600-0e90-4a18-be92-4cfcdb140616

# 본인SMS인증 채널
portone.identity2.channel-key=channel-key-c8ae2753-8311-4623-83e6-b196b6310883

# Kakao Login
kakao.client_id=3f92d7a7471b7af842f6b5b5b1bd9fbf
kakao.client_secret=YiUdUlp5y8P0lWmjDOeC6mqZX0qAJPNq
kakao.redirect_uri=http://localhost:8080/oditji/member/kakao/callback


# TMDB API settings
# Put the TMDB API Read Access Token here for local testing.
# Do not commit a real token to a public repository.
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4YzU1ZDVkYjE1YzJjODkyYWFlM2E4M2Y4YzZmZGUzNiIsIm5iZiI6MTc4MTU3OTYyMC43NCwic3ViIjoiNmEzMGJmNjQ0MThlMDQ2ZWFjM2M3NDI5Iiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.145SQGaISZ2Pb9sE0AftW6dQbTnOfmkZgzcEDNRDhh0
tmdb.api.image-base-url=https://image.tmdb.org/t/p/w500
tmdb.api.language=ko-KR
tmdb.api.region=KR
